### ISSUE TITLE
NPE caused by missing file "refresh2.png"

### ISSUE THREAD

**Issue by EdgeCaseBerg** [AlejandroRepo/WOHMakerEV#2]
Hi, running the `javafx:run` command for maven and I ran into this error:

```
Caused by: java.lang.NullPointerException
        at EventMaker/eventmaker.Controller.prepareUI(Controller.java:488)
        at EventMaker/eventmaker.Controller.initialize(Controller.java:453)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2573)
```

Tracing that line it points to

```
btnCLear.setGraphic(new ImageView(new Image(Controller.class.getResource("/refresh2.png").toExternalForm())));
```

It looks like that file is missing from the repository. Any chance you could add it so that the app isn't broken?

**Comment by AlejandroRepo** [comment]
Hey there, thanks for the report. I'll take a look at it as soon as possible.
